# Algebra plugins library, part of the ACTS project (R&D line)
#
# (c) 2021 CERN for the benefit of the ACTS project
#
# Mozilla Public License Version 2.0

name: Builds

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    # The different build modes to test.
    strategy:
      matrix:
        BUILD_TYPE: [ "Release", "Debug" ]
        SCALAR_TYPE: [ "double", "float" ]
        CMAKE_OPTIONS:
          - -DALGEBRA_PLUGIN_INCLUDE_ARRAY=TRUE
          - -DALGEBRA_PLUGIN_INCLUDE_EIGEN=TRUE -DALGEBRA_PLUGIN_SETUP_EIGEN3=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_EIGEN3=TRUE
          - -DALGEBRA_PLUGIN_INCLUDE_EIGEN=TRUE -DALGEBRA_PLUGIN_SETUP_EIGEN3=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_EIGEN3=FALSE
          - -DALGEBRA_PLUGIN_INCLUDE_VC=TRUE -DALGEBRA_PLUGIN_SETUP_VC=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VC=FALSE
          - -DALGEBRA_PLUGIN_INCLUDE_VECMEM=TRUE -DALGEBRA_PLUGIN_SETUP_VECMEM=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VECMEM=FALSE
          - -DALGEBRA_PLUGIN_INCLUDE_ARRAY=TRUE -DALGEBRA_PLUGIN_INCLUDE_EIGEN=TRUE -DALGEBRA_PLUGIN_SETUP_EIGEN3=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_EIGEN3=TRUE -DALGEBRA_PLUGIN_INCLUDE_VC=TRUE -DALGEBRA_PLUGIN_SETUP_VC=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VC=FALSE -DALGEBRA_PLUGIN_INCLUDE_VECMEM=TRUE -DALGEBRA_PLUGIN_SETUP_VECMEM=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VECMEM=FALSE

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install libeigen3-dev

    - name: Configure CMake
      shell: bash
      run: cmake -S ${{ github.workspace }} -B ${{runner.workspace}}/build
             -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
             -DALGEBRA_PLUGIN_CUSTOM_SCALARTYPE=${{ matrix.SCALAR_TYPE }}
             ${{ matrix.CMAKE_OPTIONS }}

    - name: Build
      shell: bash
      run: cmake --build ${{runner.workspace}}/build
                 --config ${{ matrix.BUILD_TYPE }}

    - name: Unit Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C ${{ matrix.BUILD_TYPE }}

  macos:
    runs-on: macos-latest

    # The different build modes to test.
    strategy:
      matrix:
        BUILD_TYPE: [ "Release", "Debug" ]
        SCALAR_TYPE: [ "double", "float" ]
        CMAKE_OPTIONS:
          - -DALGEBRA_PLUGIN_INCLUDE_ARRAY=TRUE
          - -DALGEBRA_PLUGIN_INCLUDE_EIGEN=TRUE -DALGEBRA_PLUGIN_SETUP_EIGEN3=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_EIGEN3=TRUE
          - -DALGEBRA_PLUGIN_INCLUDE_EIGEN=TRUE -DALGEBRA_PLUGIN_SETUP_EIGEN3=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_EIGEN3=FALSE
          - -DALGEBRA_PLUGIN_INCLUDE_VC=TRUE -DALGEBRA_PLUGIN_SETUP_VC=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VC=FALSE
          - -DALGEBRA_PLUGIN_INCLUDE_VECMEM=TRUE -DALGEBRA_PLUGIN_SETUP_VECMEM=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VECMEM=FALSE
          - -DALGEBRA_PLUGIN_INCLUDE_ARRAY=TRUE -DALGEBRA_PLUGIN_INCLUDE_EIGEN=TRUE -DALGEBRA_PLUGIN_SETUP_EIGEN3=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_EIGEN3=TRUE -DALGEBRA_PLUGIN_INCLUDE_VC=TRUE -DALGEBRA_PLUGIN_SETUP_VC=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VC=FALSE -DALGEBRA_PLUGIN_INCLUDE_VECMEM=TRUE -DALGEBRA_PLUGIN_SETUP_VECMEM=TRUE -DALGEBRA_PLUGIN_USE_SYSTEM_VECMEM=FALSE

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install cmake eigen ninja

    - name: Configure CMake
      shell: bash
      run: cmake -S ${{ github.workspace }} -B ${{runner.workspace}}/build
             -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
             -DALGEBRA_PLUGIN_CUSTOM_SCALARTYPE=${{ matrix.SCALAR_TYPE }}
             ${{ matrix.CMAKE_OPTIONS }}

    - name: Build
      shell: bash
      run: cmake --build ${{runner.workspace}}/build
                 --config ${{ matrix.BUILD_TYPE }}

    - name: Unit Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C ${{ matrix.BUILD_TYPE }}
