# Algebra plugins library, part of the ACTS project (R&D line)
#
# (c) 2021-2024 CERN for the benefit of the ACTS project
#
# Mozilla Public License Version 2.0

name: Checks

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'

# Cancel existing jobs on new pushes.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/format10:v11
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: .github/check_format.sh .
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: changed
          path: changed
